// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0

package store

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgtype"
)

type Coach struct {
	ID          uuid.UUID      `json:"id"`
	UserID      uuid.NullUUID  `json:"user_id"`
	Bio         sql.NullString `json:"bio"`
	Specialties []string       `json:"specialties"`
	HourlyRate  pgtype.Numeric `json:"hourly_rate"`
	IsVerified  sql.NullBool   `json:"is_verified"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
}

type CoachingSession struct {
	ID              uuid.UUID      `json:"id"`
	CoachID         uuid.NullUUID  `json:"coach_id"`
	ClientID        uuid.NullUUID  `json:"client_id"`
	ScheduledAt     time.Time      `json:"scheduled_at"`
	DurationMinutes int32          `json:"duration_minutes"`
	Status          string         `json:"status"`
	Notes           sql.NullString `json:"notes"`
	CreatedAt       time.Time      `json:"created_at"`
	UpdatedAt       time.Time      `json:"updated_at"`
}

type Food struct {
	ID          uuid.UUID      `json:"id"`
	Name        string         `json:"name"`
	Brand       sql.NullString `json:"brand"`
	ServingSize pgtype.Numeric `json:"serving_size"`
	ServingUnit sql.NullString `json:"serving_unit"`
	Calories    sql.NullInt32  `json:"calories"`
	ProteinG    pgtype.Numeric `json:"protein_g"`
	CarbsG      pgtype.Numeric `json:"carbs_g"`
	FatG        pgtype.Numeric `json:"fat_g"`
	FiberG      pgtype.Numeric `json:"fiber_g"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
}

type FoodLog struct {
	ID        uuid.UUID      `json:"id"`
	UserID    uuid.NullUUID  `json:"user_id"`
	FoodID    uuid.NullUUID  `json:"food_id"`
	Servings  pgtype.Numeric `json:"servings"`
	MealType  sql.NullString `json:"meal_type"`
	LoggedAt  time.Time      `json:"logged_at"`
	Notes     sql.NullString `json:"notes"`
	CreatedAt time.Time      `json:"created_at"`
}

type User struct {
	ID           uuid.UUID      `json:"id"`
	Email        string         `json:"email"`
	PasswordHash string         `json:"password_hash"`
	FirstName    sql.NullString `json:"first_name"`
	LastName     sql.NullString `json:"last_name"`
	CreatedAt    time.Time      `json:"created_at"`
	UpdatedAt    time.Time      `json:"updated_at"`
}

type UserProfile struct {
	UserID             uuid.UUID      `json:"user_id"`
	HeightCm           sql.NullInt32  `json:"height_cm"`
	WeightKg           pgtype.Numeric `json:"weight_kg"`
	Goal               sql.NullString `json:"goal"`
	TrackingPreference sql.NullString `json:"tracking_preference"`
	DailyCalorieTarget sql.NullInt32  `json:"daily_calorie_target"`
	CreatedAt          time.Time      `json:"created_at"`
	UpdatedAt          time.Time      `json:"updated_at"`
}
